### ISSUE TITLE
Projection API

### ISSUE THREAD

**Issue by pounard** [makinacorpus/php-goat#11]
Projections should be handled by its own manager/handler/<call it as you like>, general idea is:

 - when an event happened, dispatch it via a bus,
 - deal with projections asynchronously.

Because ideal world does not exists and we today have infrastructure limitations:

 - write a worker than can be run via a cron regularly,
 - it needs to store last processed event, so when it's stopped, it can resume, this need to be reliable storage (SQL, some file?),
 - it needs to log errors, mark projectors as being errenous, store state of each projector and the last event then consume, the last error that happened,
 - since it'll run as a PHP cron command, handle max run time and memory limit consumption properly,
 - instrumentation everywhere!
 - ideally, store statistics/timings somewhere (sql table, other).

Some random ideas:

 - have an interface for projector (dispatch[Event])
 - have a PHP implementation: uses the ProjectorRepository and run projections 
 - implement a worker that processes X events, from position Y or date D.

**Comment by pounard** [comment]
Note for myself: this could be a completely separated package, that could be used standalone, or embedded as a library into a wider monolith project.

**Comment by regilero** [comment]
Are there any order/priority/sequencing problems with projections?

**Comment by pounard** [comment]
They should be independent, in theory. Any inter-dependency is a design error.
